/********************************************************************************
** Form generated from reading UI file 'NewEntity.ui'
**
** Created by: Qt User Interface Compiler version 5.10.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_NEWENTITY_H
#define UI_NEWENTITY_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QRadioButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_NewEntForm
{
public:
    QTabWidget *tabWidget;
    QWidget *tab;
    QCheckBox *checkBox;
    QFrame *frame;
    QDoubleSpinBox *doubleSpinBox_3;
    QLabel *label;
    QLabel *label_2;
    QDoubleSpinBox *doubleSpinBox_2;
    QDoubleSpinBox *doubleSpinBox;
    QLabel *label_3;
    QFrame *frame_2;
    QDoubleSpinBox *doubleSpinBox_8;
    QLabel *label_8;
    QLabel *label_9;
    QDoubleSpinBox *doubleSpinBox_9;
    QDoubleSpinBox *doubleSpinBox_10;
    QLabel *label_10;
    QFrame *frame_5;
    QDoubleSpinBox *doubleSpinBox_18;
    QLabel *label_18;
    QLabel *label_19;
    QDoubleSpinBox *doubleSpinBox_19;
    QDoubleSpinBox *doubleSpinBox_20;
    QLabel *label_20;
    QFrame *frame_6;
    QDoubleSpinBox *doubleSpinBox_21;
    QLabel *label_21;
    QLabel *label_22;
    QDoubleSpinBox *doubleSpinBox_22;
    QDoubleSpinBox *doubleSpinBox_23;
    QLabel *label_23;
    QFrame *frame_7;
    QRadioButton *radioButton;
    QDoubleSpinBox *doubleSpinBox_4;
    QLabel *label_4;
    QWidget *tab_2;
    QFrame *frame_8;
    QDoubleSpinBox *doubleSpinBox_24;
    QLabel *label_24;
    QLabel *label_25;
    QDoubleSpinBox *doubleSpinBox_25;
    QDoubleSpinBox *doubleSpinBox_26;
    QLabel *label_26;
    QFrame *frame_9;
    QDoubleSpinBox *doubleSpinBox_27;
    QLabel *label_27;
    QDoubleSpinBox *doubleSpinBox_28;
    QDoubleSpinBox *doubleSpinBox_29;
    QLabel *label_28;
    QLabel *label_29;
    QCheckBox *checkBox_3;
    QWidget *tab_3;
    QFrame *frame_10;
    QDoubleSpinBox *doubleSpinBox_30;
    QLabel *label_30;
    QLabel *label_31;
    QDoubleSpinBox *doubleSpinBox_31;
    QDoubleSpinBox *doubleSpinBox_32;
    QLabel *label_32;
    QFrame *frame_11;
    QDoubleSpinBox *doubleSpinBox_33;
    QLabel *label_33;
    QCheckBox *checkBox_4;
    QWidget *tab_4;
    QFrame *frame_12;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QSpinBox *spinBox;
    QSpinBox *spinBox_2;
    QSpinBox *spinBox_3;
    QComboBox *comboBox;
    QLabel *label_37;
    QCheckBox *checkBox_5;
    QWidget *tab_5;
    QFrame *frame_13;
    QLabel *label_38;
    QLabel *label_39;
    QSpinBox *spinBox_4;
    QSpinBox *spinBox_5;
    QCheckBox *checkBox_10;
    QCheckBox *checkBox_6;
    QWidget *tab_6;
    QLabel *label_40;
    QLabel *label_41;
    QFrame *frame_14;
    QRadioButton *radioButton_2;
    QSpinBox *spinBox_6;
    QSpinBox *spinBox_7;
    QCheckBox *checkBox_7;
    QComboBox *comboBox_2;
    QLabel *label_42;
    QComboBox *comboBox_3;
    QLabel *label_43;
    QComboBox *comboBox_4;
    QLabel *label_44;
    QFrame *frame_15;
    QWidget *tab_7;
    QLabel *label_45;
    QDoubleSpinBox *doubleSpinBox_37;
    QCheckBox *checkBox_8;
    QCheckBox *checkBox_2;
    QCheckBox *checkBox_13;
    QCheckBox *checkBox_14;
    QCheckBox *checkBox_15;
    QCheckBox *checkBox_16;
    QCheckBox *checkBox_17;
    QGroupBox *groupBox;
    QWidget *tab_8;
    QDoubleSpinBox *doubleSpinBox_40;
    QDoubleSpinBox *doubleSpinBox_41;
    QLabel *label_47;
    QLabel *label_48;
    QFrame *frame_16;
    QLabel *label_49;
    QLabel *label_50;
    QComboBox *comboBox_6;
    QLabel *label_51;
    QCheckBox *checkBox_9;
    QSpinBox *spinBox_8;
    QSpinBox *spinBox_9;
    QPushButton *pushButton_4;
    QRadioButton *radioButton_3;
    QLabel *label_52;
    QDoubleSpinBox *doubleSpinBox_42;
    QDoubleSpinBox *doubleSpinBox_43;
    QFrame *frame_17;
    QLabel *label_53;
    QWidget *tab_9;
    QFrame *frame_18;
    QLabel *label_119;
    QDoubleSpinBox *doubleSpinBox_67;
    QFrame *frame_19;
    QLabel *label_118;
    QLabel *label_117;
    QDoubleSpinBox *doubleSpinBox_65;
    QDoubleSpinBox *doubleSpinBox_66;
    QLabel *label_114;
    QLabel *label_116;
    QLabel *label_110;
    QFrame *frame_20;
    QLabel *label_111;
    QFrame *frame_21;
    QLabel *label_115;
    QDoubleSpinBox *doubleSpinBox_64;
    QCheckBox *checkBox_11;
    QWidget *tab_10;
    QCheckBox *checkBox_12;
    QPushButton *pushButton;
    QPushButton *pushButton_2;
    QFrame *line_2;

    void setupUi(QWidget *NewEntForm)
    {
        if (NewEntForm->objectName().isEmpty())
            NewEntForm->setObjectName(QStringLiteral("NewEntForm"));
        NewEntForm->resize(662, 336);
        tabWidget = new QTabWidget(NewEntForm);
        tabWidget->setObjectName(QStringLiteral("tabWidget"));
        tabWidget->setGeometry(QRect(10, 20, 631, 261));
        tabWidget->setTabsClosable(false);
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        checkBox = new QCheckBox(tab);
        checkBox->setObjectName(QStringLiteral("checkBox"));
        checkBox->setGeometry(QRect(20, 190, 121, 17));
        checkBox->setChecked(true);
        frame = new QFrame(tab);
        frame->setObjectName(QStringLiteral("frame"));
        frame->setGeometry(QRect(20, 20, 191, 141));
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        doubleSpinBox_3 = new QDoubleSpinBox(frame);
        doubleSpinBox_3->setObjectName(QStringLiteral("doubleSpinBox_3"));
        doubleSpinBox_3->setGeometry(QRect(80, 90, 62, 22));
        doubleSpinBox_3->setProperty("showGroupSeparator", QVariant(false));
        label = new QLabel(frame);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(30, 30, 47, 13));
        label_2 = new QLabel(frame);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(29, 62, 47, 13));
        doubleSpinBox_2 = new QDoubleSpinBox(frame);
        doubleSpinBox_2->setObjectName(QStringLiteral("doubleSpinBox_2"));
        doubleSpinBox_2->setGeometry(QRect(80, 58, 62, 22));
        doubleSpinBox_2->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox = new QDoubleSpinBox(frame);
        doubleSpinBox->setObjectName(QStringLiteral("doubleSpinBox"));
        doubleSpinBox->setGeometry(QRect(80, 26, 62, 22));
        doubleSpinBox->setProperty("showGroupSeparator", QVariant(false));
        label_3 = new QLabel(frame);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(30, 95, 47, 13));
        frame_2 = new QFrame(frame);
        frame_2->setObjectName(QStringLiteral("frame_2"));
        frame_2->setGeometry(QRect(0, 0, 191, 141));
        frame_2->setFrameShape(QFrame::StyledPanel);
        frame_2->setFrameShadow(QFrame::Raised);
        doubleSpinBox_8 = new QDoubleSpinBox(frame_2);
        doubleSpinBox_8->setObjectName(QStringLiteral("doubleSpinBox_8"));
        doubleSpinBox_8->setGeometry(QRect(80, 90, 62, 22));
        doubleSpinBox_8->setProperty("showGroupSeparator", QVariant(false));
        label_8 = new QLabel(frame_2);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(30, 30, 47, 13));
        label_9 = new QLabel(frame_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(29, 62, 47, 13));
        doubleSpinBox_9 = new QDoubleSpinBox(frame_2);
        doubleSpinBox_9->setObjectName(QStringLiteral("doubleSpinBox_9"));
        doubleSpinBox_9->setGeometry(QRect(80, 58, 62, 22));
        doubleSpinBox_9->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_10 = new QDoubleSpinBox(frame_2);
        doubleSpinBox_10->setObjectName(QStringLiteral("doubleSpinBox_10"));
        doubleSpinBox_10->setGeometry(QRect(80, 26, 62, 22));
        doubleSpinBox_10->setProperty("showGroupSeparator", QVariant(false));
        label_10 = new QLabel(frame_2);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(30, 95, 47, 13));
        frame_5 = new QFrame(frame_2);
        frame_5->setObjectName(QStringLiteral("frame_5"));
        frame_5->setGeometry(QRect(0, 0, 191, 141));
        frame_5->setFrameShape(QFrame::StyledPanel);
        frame_5->setFrameShadow(QFrame::Raised);
        doubleSpinBox_18 = new QDoubleSpinBox(frame_5);
        doubleSpinBox_18->setObjectName(QStringLiteral("doubleSpinBox_18"));
        doubleSpinBox_18->setGeometry(QRect(80, 90, 62, 22));
        doubleSpinBox_18->setProperty("showGroupSeparator", QVariant(false));
        label_18 = new QLabel(frame_5);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(30, 30, 47, 13));
        label_19 = new QLabel(frame_5);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(29, 62, 47, 13));
        doubleSpinBox_19 = new QDoubleSpinBox(frame_5);
        doubleSpinBox_19->setObjectName(QStringLiteral("doubleSpinBox_19"));
        doubleSpinBox_19->setGeometry(QRect(80, 58, 62, 22));
        doubleSpinBox_19->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_20 = new QDoubleSpinBox(frame_5);
        doubleSpinBox_20->setObjectName(QStringLiteral("doubleSpinBox_20"));
        doubleSpinBox_20->setGeometry(QRect(80, 26, 62, 22));
        doubleSpinBox_20->setProperty("showGroupSeparator", QVariant(false));
        label_20 = new QLabel(frame_5);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(30, 95, 47, 13));
        frame_6 = new QFrame(frame_5);
        frame_6->setObjectName(QStringLiteral("frame_6"));
        frame_6->setGeometry(QRect(0, 0, 191, 161));
        frame_6->setFrameShape(QFrame::StyledPanel);
        frame_6->setFrameShadow(QFrame::Raised);
        doubleSpinBox_21 = new QDoubleSpinBox(frame_6);
        doubleSpinBox_21->setObjectName(QStringLiteral("doubleSpinBox_21"));
        doubleSpinBox_21->setEnabled(false);
        doubleSpinBox_21->setGeometry(QRect(80, 90, 62, 22));
        doubleSpinBox_21->setProperty("showGroupSeparator", QVariant(false));
        label_21 = new QLabel(frame_6);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(30, 30, 47, 13));
        label_22 = new QLabel(frame_6);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(29, 62, 47, 13));
        doubleSpinBox_22 = new QDoubleSpinBox(frame_6);
        doubleSpinBox_22->setObjectName(QStringLiteral("doubleSpinBox_22"));
        doubleSpinBox_22->setGeometry(QRect(80, 58, 62, 22));
        doubleSpinBox_22->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_22->setMaximum(9999);
        doubleSpinBox_23 = new QDoubleSpinBox(frame_6);
        doubleSpinBox_23->setObjectName(QStringLiteral("doubleSpinBox_23"));
        doubleSpinBox_23->setGeometry(QRect(80, 26, 62, 22));
        doubleSpinBox_23->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_23->setMaximum(9999);
        label_23 = new QLabel(frame_6);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(30, 95, 47, 13));
        frame_7 = new QFrame(tab);
        frame_7->setObjectName(QStringLiteral("frame_7"));
        frame_7->setGeometry(QRect(220, 20, 151, 141));
        frame_7->setFrameShape(QFrame::StyledPanel);
        frame_7->setFrameShadow(QFrame::Raised);
        radioButton = new QRadioButton(frame_7);
        radioButton->setObjectName(QStringLiteral("radioButton"));
        radioButton->setGeometry(QRect(30, 110, 82, 17));
        doubleSpinBox_4 = new QDoubleSpinBox(frame_7);
        doubleSpinBox_4->setObjectName(QStringLiteral("doubleSpinBox_4"));
        doubleSpinBox_4->setGeometry(QRect(70, 40, 62, 22));
        doubleSpinBox_4->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_4->setMinimum(0);
        doubleSpinBox_4->setMaximum(360);
        label_4 = new QLabel(frame_7);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(21, 45, 47, 13));
        tabWidget->addTab(tab, QString());
        frame_7->raise();
        frame->raise();
        checkBox->raise();
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        frame_8 = new QFrame(tab_2);
        frame_8->setObjectName(QStringLiteral("frame_8"));
        frame_8->setGeometry(QRect(10, 20, 191, 161));
        frame_8->setFrameShape(QFrame::StyledPanel);
        frame_8->setFrameShadow(QFrame::Raised);
        doubleSpinBox_24 = new QDoubleSpinBox(frame_8);
        doubleSpinBox_24->setObjectName(QStringLiteral("doubleSpinBox_24"));
        doubleSpinBox_24->setEnabled(false);
        doubleSpinBox_24->setGeometry(QRect(80, 90, 62, 22));
        doubleSpinBox_24->setProperty("showGroupSeparator", QVariant(false));
        label_24 = new QLabel(frame_8);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(30, 30, 47, 13));
        label_25 = new QLabel(frame_8);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(29, 62, 47, 13));
        doubleSpinBox_25 = new QDoubleSpinBox(frame_8);
        doubleSpinBox_25->setObjectName(QStringLiteral("doubleSpinBox_25"));
        doubleSpinBox_25->setEnabled(false);
        doubleSpinBox_25->setGeometry(QRect(80, 58, 62, 22));
        doubleSpinBox_25->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_25->setMaximum(300);
        doubleSpinBox_26 = new QDoubleSpinBox(frame_8);
        doubleSpinBox_26->setObjectName(QStringLiteral("doubleSpinBox_26"));
        doubleSpinBox_26->setEnabled(false);
        doubleSpinBox_26->setGeometry(QRect(80, 26, 62, 22));
        doubleSpinBox_26->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_26->setMaximum(300);
        label_26 = new QLabel(frame_8);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(30, 95, 47, 13));
        frame_9 = new QFrame(tab_2);
        frame_9->setObjectName(QStringLiteral("frame_9"));
        frame_9->setGeometry(QRect(220, 20, 191, 161));
        frame_9->setFrameShape(QFrame::StyledPanel);
        frame_9->setFrameShadow(QFrame::Raised);
        doubleSpinBox_27 = new QDoubleSpinBox(frame_9);
        doubleSpinBox_27->setObjectName(QStringLiteral("doubleSpinBox_27"));
        doubleSpinBox_27->setEnabled(false);
        doubleSpinBox_27->setGeometry(QRect(80, 90, 62, 22));
        doubleSpinBox_27->setProperty("showGroupSeparator", QVariant(false));
        label_27 = new QLabel(frame_9);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(20, 29, 61, 16));
        doubleSpinBox_28 = new QDoubleSpinBox(frame_9);
        doubleSpinBox_28->setObjectName(QStringLiteral("doubleSpinBox_28"));
        doubleSpinBox_28->setEnabled(false);
        doubleSpinBox_28->setGeometry(QRect(80, 58, 62, 22));
        doubleSpinBox_28->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_28->setMaximum(300);
        doubleSpinBox_29 = new QDoubleSpinBox(frame_9);
        doubleSpinBox_29->setObjectName(QStringLiteral("doubleSpinBox_29"));
        doubleSpinBox_29->setEnabled(false);
        doubleSpinBox_29->setGeometry(QRect(80, 26, 62, 22));
        doubleSpinBox_29->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_29->setMaximum(300);
        label_28 = new QLabel(frame_9);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(20, 60, 61, 16));
        label_29 = new QLabel(frame_9);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(20, 90, 61, 16));
        checkBox_3 = new QCheckBox(tab_2);
        checkBox_3->setObjectName(QStringLiteral("checkBox_3"));
        checkBox_3->setGeometry(QRect(10, 190, 121, 17));
        tabWidget->addTab(tab_2, QString());
        tab_3 = new QWidget();
        tab_3->setObjectName(QStringLiteral("tab_3"));
        frame_10 = new QFrame(tab_3);
        frame_10->setObjectName(QStringLiteral("frame_10"));
        frame_10->setGeometry(QRect(10, 20, 191, 161));
        frame_10->setFrameShape(QFrame::StyledPanel);
        frame_10->setFrameShadow(QFrame::Raised);
        doubleSpinBox_30 = new QDoubleSpinBox(frame_10);
        doubleSpinBox_30->setObjectName(QStringLiteral("doubleSpinBox_30"));
        doubleSpinBox_30->setEnabled(false);
        doubleSpinBox_30->setGeometry(QRect(80, 90, 62, 22));
        doubleSpinBox_30->setProperty("showGroupSeparator", QVariant(false));
        label_30 = new QLabel(frame_10);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(30, 30, 47, 13));
        label_31 = new QLabel(frame_10);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(29, 62, 47, 13));
        doubleSpinBox_31 = new QDoubleSpinBox(frame_10);
        doubleSpinBox_31->setObjectName(QStringLiteral("doubleSpinBox_31"));
        doubleSpinBox_31->setEnabled(false);
        doubleSpinBox_31->setGeometry(QRect(80, 58, 62, 22));
        doubleSpinBox_31->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_31->setMaximum(300);
        doubleSpinBox_32 = new QDoubleSpinBox(frame_10);
        doubleSpinBox_32->setObjectName(QStringLiteral("doubleSpinBox_32"));
        doubleSpinBox_32->setEnabled(false);
        doubleSpinBox_32->setGeometry(QRect(80, 26, 62, 22));
        doubleSpinBox_32->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_32->setMaximum(300);
        label_32 = new QLabel(frame_10);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(30, 95, 47, 13));
        frame_11 = new QFrame(tab_3);
        frame_11->setObjectName(QStringLiteral("frame_11"));
        frame_11->setGeometry(QRect(210, 20, 151, 161));
        frame_11->setFrameShape(QFrame::StyledPanel);
        frame_11->setFrameShadow(QFrame::Raised);
        doubleSpinBox_33 = new QDoubleSpinBox(frame_11);
        doubleSpinBox_33->setObjectName(QStringLiteral("doubleSpinBox_33"));
        doubleSpinBox_33->setEnabled(false);
        doubleSpinBox_33->setGeometry(QRect(60, 60, 62, 22));
        doubleSpinBox_33->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_33->setMinimum(0);
        doubleSpinBox_33->setMaximum(300);
        label_33 = new QLabel(frame_11);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(29, 65, 47, 13));
        checkBox_4 = new QCheckBox(tab_3);
        checkBox_4->setObjectName(QStringLiteral("checkBox_4"));
        checkBox_4->setGeometry(QRect(10, 200, 121, 17));
        tabWidget->addTab(tab_3, QString());
        tab_4 = new QWidget();
        tab_4->setObjectName(QStringLiteral("tab_4"));
        frame_12 = new QFrame(tab_4);
        frame_12->setObjectName(QStringLiteral("frame_12"));
        frame_12->setGeometry(QRect(20, 30, 191, 151));
        frame_12->setFrameShape(QFrame::StyledPanel);
        frame_12->setFrameShadow(QFrame::Raised);
        label_34 = new QLabel(frame_12);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(40, 30, 47, 13));
        label_35 = new QLabel(frame_12);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(50, 62, 47, 13));
        label_36 = new QLabel(frame_12);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(47, 94, 47, 13));
        spinBox = new QSpinBox(frame_12);
        spinBox->setObjectName(QStringLiteral("spinBox"));
        spinBox->setEnabled(false);
        spinBox->setGeometry(QRect(90, 25, 42, 22));
        spinBox_2 = new QSpinBox(frame_12);
        spinBox_2->setObjectName(QStringLiteral("spinBox_2"));
        spinBox_2->setEnabled(false);
        spinBox_2->setGeometry(QRect(90, 60, 42, 22));
        spinBox_3 = new QSpinBox(frame_12);
        spinBox_3->setObjectName(QStringLiteral("spinBox_3"));
        spinBox_3->setEnabled(false);
        spinBox_3->setGeometry(QRect(90, 90, 42, 22));
        comboBox = new QComboBox(tab_4);
        comboBox->addItem(QString());
        comboBox->addItem(QString());
        comboBox->setObjectName(QStringLiteral("comboBox"));
        comboBox->setEnabled(false);
        comboBox->setGeometry(QRect(270, 80, 141, 22));
        comboBox->setEditable(false);
        comboBox->setMaxVisibleItems(2);
        comboBox->setInsertPolicy(QComboBox::InsertAtBottom);
        comboBox->setMinimumContentsLength(1);
        comboBox->setFrame(true);
        comboBox->setModelColumn(0);
        label_37 = new QLabel(tab_4);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(239, 83, 47, 13));
        checkBox_5 = new QCheckBox(tab_4);
        checkBox_5->setObjectName(QStringLiteral("checkBox_5"));
        checkBox_5->setGeometry(QRect(20, 200, 121, 17));
        tabWidget->addTab(tab_4, QString());
        tab_5 = new QWidget();
        tab_5->setObjectName(QStringLiteral("tab_5"));
        frame_13 = new QFrame(tab_5);
        frame_13->setObjectName(QStringLiteral("frame_13"));
        frame_13->setGeometry(QRect(20, 20, 191, 111));
        frame_13->setFrameShape(QFrame::StyledPanel);
        frame_13->setFrameShadow(QFrame::Raised);
        label_38 = new QLabel(frame_13);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(23, 28, 61, 16));
        label_39 = new QLabel(frame_13);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(50, 62, 47, 13));
        spinBox_4 = new QSpinBox(frame_13);
        spinBox_4->setObjectName(QStringLiteral("spinBox_4"));
        spinBox_4->setEnabled(false);
        spinBox_4->setGeometry(QRect(80, 60, 42, 22));
        spinBox_5 = new QSpinBox(frame_13);
        spinBox_5->setObjectName(QStringLiteral("spinBox_5"));
        spinBox_5->setEnabled(false);
        spinBox_5->setGeometry(QRect(80, 25, 42, 22));
        checkBox_10 = new QCheckBox(frame_13);
        checkBox_10->setObjectName(QStringLiteral("checkBox_10"));
        checkBox_10->setGeometry(QRect(0, 120, 121, 17));
        checkBox_6 = new QCheckBox(tab_5);
        checkBox_6->setObjectName(QStringLiteral("checkBox_6"));
        checkBox_6->setGeometry(QRect(20, 140, 121, 17));
        tabWidget->addTab(tab_5, QString());
        tab_6 = new QWidget();
        tab_6->setObjectName(QStringLiteral("tab_6"));
        label_40 = new QLabel(tab_6);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(57, 55, 47, 13));
        label_41 = new QLabel(tab_6);
        label_41->setObjectName(QStringLiteral("label_41"));
        label_41->setGeometry(QRect(53, 89, 47, 13));
        frame_14 = new QFrame(tab_6);
        frame_14->setObjectName(QStringLiteral("frame_14"));
        frame_14->setGeometry(QRect(30, 30, 231, 151));
        frame_14->setFrameShape(QFrame::StyledPanel);
        frame_14->setFrameShadow(QFrame::Raised);
        radioButton_2 = new QRadioButton(frame_14);
        radioButton_2->setObjectName(QStringLiteral("radioButton_2"));
        radioButton_2->setEnabled(false);
        radioButton_2->setGeometry(QRect(20, 100, 101, 17));
        spinBox_6 = new QSpinBox(frame_14);
        spinBox_6->setObjectName(QStringLiteral("spinBox_6"));
        spinBox_6->setEnabled(false);
        spinBox_6->setGeometry(QRect(80, 20, 61, 22));
        spinBox_6->setMaximum(9999);
        spinBox_7 = new QSpinBox(frame_14);
        spinBox_7->setObjectName(QStringLiteral("spinBox_7"));
        spinBox_7->setEnabled(false);
        spinBox_7->setGeometry(QRect(80, 53, 61, 22));
        spinBox_7->setMaximum(9999);
        checkBox_7 = new QCheckBox(tab_6);
        checkBox_7->setObjectName(QStringLiteral("checkBox_7"));
        checkBox_7->setGeometry(QRect(30, 190, 121, 17));
        comboBox_2 = new QComboBox(tab_6);
        comboBox_2->addItem(QString());
        comboBox_2->setObjectName(QStringLiteral("comboBox_2"));
        comboBox_2->setEnabled(false);
        comboBox_2->setGeometry(QRect(400, 60, 151, 22));
        label_42 = new QLabel(tab_6);
        label_42->setObjectName(QStringLiteral("label_42"));
        label_42->setGeometry(QRect(310, 62, 111, 16));
        comboBox_3 = new QComboBox(tab_6);
        comboBox_3->addItem(QString());
        comboBox_3->addItem(QString());
        comboBox_3->addItem(QString());
        comboBox_3->setObjectName(QStringLiteral("comboBox_3"));
        comboBox_3->setEnabled(false);
        comboBox_3->setGeometry(QRect(400, 100, 151, 22));
        label_43 = new QLabel(tab_6);
        label_43->setObjectName(QStringLiteral("label_43"));
        label_43->setGeometry(QRect(300, 102, 111, 16));
        comboBox_4 = new QComboBox(tab_6);
        comboBox_4->addItem(QString());
        comboBox_4->setObjectName(QStringLiteral("comboBox_4"));
        comboBox_4->setEnabled(false);
        comboBox_4->setGeometry(QRect(400, 140, 151, 22));
        label_44 = new QLabel(tab_6);
        label_44->setObjectName(QStringLiteral("label_44"));
        label_44->setGeometry(QRect(350, 142, 111, 16));
        frame_15 = new QFrame(tab_6);
        frame_15->setObjectName(QStringLiteral("frame_15"));
        frame_15->setGeometry(QRect(290, 30, 301, 151));
        frame_15->setFrameShape(QFrame::StyledPanel);
        frame_15->setFrameShadow(QFrame::Raised);
        tabWidget->addTab(tab_6, QString());
        frame_15->raise();
        frame_14->raise();
        label_40->raise();
        label_41->raise();
        checkBox_7->raise();
        comboBox_2->raise();
        label_42->raise();
        comboBox_3->raise();
        label_43->raise();
        comboBox_4->raise();
        label_44->raise();
        tab_7 = new QWidget();
        tab_7->setObjectName(QStringLiteral("tab_7"));
        label_45 = new QLabel(tab_7);
        label_45->setObjectName(QStringLiteral("label_45"));
        label_45->setGeometry(QRect(20, 44, 47, 13));
        doubleSpinBox_37 = new QDoubleSpinBox(tab_7);
        doubleSpinBox_37->setObjectName(QStringLiteral("doubleSpinBox_37"));
        doubleSpinBox_37->setEnabled(false);
        doubleSpinBox_37->setGeometry(QRect(70, 40, 62, 22));
        doubleSpinBox_37->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_37->setMaximum(1);
        checkBox_8 = new QCheckBox(tab_7);
        checkBox_8->setObjectName(QStringLiteral("checkBox_8"));
        checkBox_8->setGeometry(QRect(20, 90, 121, 17));
        checkBox_8->setChecked(false);
        checkBox_2 = new QCheckBox(tab_7);
        checkBox_2->setObjectName(QStringLiteral("checkBox_2"));
        checkBox_2->setGeometry(QRect(190, 40, 70, 17));
        checkBox_13 = new QCheckBox(tab_7);
        checkBox_13->setObjectName(QStringLiteral("checkBox_13"));
        checkBox_13->setGeometry(QRect(190, 60, 70, 17));
        checkBox_14 = new QCheckBox(tab_7);
        checkBox_14->setObjectName(QStringLiteral("checkBox_14"));
        checkBox_14->setGeometry(QRect(190, 80, 70, 17));
        checkBox_15 = new QCheckBox(tab_7);
        checkBox_15->setObjectName(QStringLiteral("checkBox_15"));
        checkBox_15->setGeometry(QRect(190, 100, 70, 17));
        checkBox_16 = new QCheckBox(tab_7);
        checkBox_16->setObjectName(QStringLiteral("checkBox_16"));
        checkBox_16->setGeometry(QRect(190, 120, 70, 17));
        checkBox_17 = new QCheckBox(tab_7);
        checkBox_17->setObjectName(QStringLiteral("checkBox_17"));
        checkBox_17->setGeometry(QRect(190, 140, 70, 17));
        groupBox = new QGroupBox(tab_7);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(179, 20, 121, 161));
        tabWidget->addTab(tab_7, QString());
        groupBox->raise();
        label_45->raise();
        doubleSpinBox_37->raise();
        checkBox_8->raise();
        checkBox_2->raise();
        checkBox_13->raise();
        checkBox_14->raise();
        checkBox_15->raise();
        checkBox_16->raise();
        checkBox_17->raise();
        tab_8 = new QWidget();
        tab_8->setObjectName(QStringLiteral("tab_8"));
        doubleSpinBox_40 = new QDoubleSpinBox(tab_8);
        doubleSpinBox_40->setObjectName(QStringLiteral("doubleSpinBox_40"));
        doubleSpinBox_40->setEnabled(false);
        doubleSpinBox_40->setGeometry(QRect(80, 68, 62, 22));
        doubleSpinBox_40->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_40->setMaximum(300);
        doubleSpinBox_41 = new QDoubleSpinBox(tab_8);
        doubleSpinBox_41->setObjectName(QStringLiteral("doubleSpinBox_41"));
        doubleSpinBox_41->setEnabled(false);
        doubleSpinBox_41->setGeometry(QRect(80, 36, 62, 22));
        doubleSpinBox_41->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_41->setMaximum(300);
        label_47 = new QLabel(tab_8);
        label_47->setObjectName(QStringLiteral("label_47"));
        label_47->setGeometry(QRect(29, 72, 47, 13));
        label_48 = new QLabel(tab_8);
        label_48->setObjectName(QStringLiteral("label_48"));
        label_48->setGeometry(QRect(30, 40, 47, 13));
        frame_16 = new QFrame(tab_8);
        frame_16->setObjectName(QStringLiteral("frame_16"));
        frame_16->setGeometry(QRect(10, 20, 161, 91));
        frame_16->setFrameShape(QFrame::StyledPanel);
        frame_16->setFrameShadow(QFrame::Raised);
        label_49 = new QLabel(tab_8);
        label_49->setObjectName(QStringLiteral("label_49"));
        label_49->setGeometry(QRect(197, 46, 61, 17));
        label_50 = new QLabel(tab_8);
        label_50->setObjectName(QStringLiteral("label_50"));
        label_50->setGeometry(QRect(223, 78, 61, 17));
        comboBox_6 = new QComboBox(tab_8);
        comboBox_6->addItem(QString());
        comboBox_6->addItem(QString());
        comboBox_6->setObjectName(QStringLiteral("comboBox_6"));
        comboBox_6->setEnabled(false);
        comboBox_6->setGeometry(QRect(441, 58, 151, 22));
        comboBox_6->setContextMenuPolicy(Qt::DefaultContextMenu);
        comboBox_6->setInsertPolicy(QComboBox::InsertAtTop);
        comboBox_6->setMinimumContentsLength(0);
        label_51 = new QLabel(tab_8);
        label_51->setObjectName(QStringLiteral("label_51"));
        label_51->setGeometry(QRect(380, 60, 111, 16));
        checkBox_9 = new QCheckBox(tab_8);
        checkBox_9->setObjectName(QStringLiteral("checkBox_9"));
        checkBox_9->setGeometry(QRect(190, 190, 121, 17));
        spinBox_8 = new QSpinBox(tab_8);
        spinBox_8->setObjectName(QStringLiteral("spinBox_8"));
        spinBox_8->setEnabled(false);
        spinBox_8->setGeometry(QRect(266, 44, 42, 22));
        spinBox_9 = new QSpinBox(tab_8);
        spinBox_9->setObjectName(QStringLiteral("spinBox_9"));
        spinBox_9->setEnabled(false);
        spinBox_9->setGeometry(QRect(267, 76, 42, 22));
        spinBox_9->setMinimum(1);
        spinBox_9->setMaximum(500);
        pushButton_4 = new QPushButton(tab_8);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setEnabled(false);
        pushButton_4->setGeometry(QRect(450, 110, 121, 23));
        radioButton_3 = new QRadioButton(tab_8);
        radioButton_3->setObjectName(QStringLiteral("radioButton_3"));
        radioButton_3->setEnabled(false);
        radioButton_3->setGeometry(QRect(440, 170, 121, 17));
        radioButton_3->setChecked(true);
        label_52 = new QLabel(tab_8);
        label_52->setObjectName(QStringLiteral("label_52"));
        label_52->setGeometry(QRect(31, 138, 47, 13));
        doubleSpinBox_42 = new QDoubleSpinBox(tab_8);
        doubleSpinBox_42->setObjectName(QStringLiteral("doubleSpinBox_42"));
        doubleSpinBox_42->setEnabled(false);
        doubleSpinBox_42->setGeometry(QRect(81, 166, 62, 22));
        doubleSpinBox_42->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_42->setMaximum(9999);
        doubleSpinBox_43 = new QDoubleSpinBox(tab_8);
        doubleSpinBox_43->setObjectName(QStringLiteral("doubleSpinBox_43"));
        doubleSpinBox_43->setEnabled(false);
        doubleSpinBox_43->setGeometry(QRect(81, 134, 62, 22));
        doubleSpinBox_43->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_43->setMaximum(9999);
        frame_17 = new QFrame(tab_8);
        frame_17->setObjectName(QStringLiteral("frame_17"));
        frame_17->setGeometry(QRect(11, 118, 161, 91));
        frame_17->setFrameShape(QFrame::StyledPanel);
        frame_17->setFrameShadow(QFrame::Raised);
        label_53 = new QLabel(tab_8);
        label_53->setObjectName(QStringLiteral("label_53"));
        label_53->setGeometry(QRect(30, 170, 47, 13));
        tabWidget->addTab(tab_8, QString());
        frame_17->raise();
        frame_16->raise();
        doubleSpinBox_40->raise();
        doubleSpinBox_41->raise();
        label_47->raise();
        label_48->raise();
        label_49->raise();
        label_50->raise();
        comboBox_6->raise();
        label_51->raise();
        checkBox_9->raise();
        spinBox_8->raise();
        spinBox_9->raise();
        pushButton_4->raise();
        radioButton_3->raise();
        label_52->raise();
        doubleSpinBox_42->raise();
        doubleSpinBox_43->raise();
        label_53->raise();
        tab_9 = new QWidget();
        tab_9->setObjectName(QStringLiteral("tab_9"));
        frame_18 = new QFrame(tab_9);
        frame_18->setObjectName(QStringLiteral("frame_18"));
        frame_18->setGeometry(QRect(30, 20, 161, 71));
        frame_18->setFrameShape(QFrame::StyledPanel);
        frame_18->setFrameShadow(QFrame::Raised);
        label_119 = new QLabel(frame_18);
        label_119->setObjectName(QStringLiteral("label_119"));
        label_119->setGeometry(QRect(30, 0, 101, 16));
        doubleSpinBox_67 = new QDoubleSpinBox(tab_9);
        doubleSpinBox_67->setObjectName(QStringLiteral("doubleSpinBox_67"));
        doubleSpinBox_67->setEnabled(false);
        doubleSpinBox_67->setGeometry(QRect(101, 44, 62, 22));
        doubleSpinBox_67->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_67->setMaximum(300);
        frame_19 = new QFrame(tab_9);
        frame_19->setObjectName(QStringLiteral("frame_19"));
        frame_19->setGeometry(QRect(210, 20, 161, 71));
        frame_19->setFrameShape(QFrame::StyledPanel);
        frame_19->setFrameShadow(QFrame::Raised);
        label_118 = new QLabel(frame_19);
        label_118->setObjectName(QStringLiteral("label_118"));
        label_118->setGeometry(QRect(50, 0, 101, 16));
        label_117 = new QLabel(tab_9);
        label_117->setObjectName(QStringLiteral("label_117"));
        label_117->setGeometry(QRect(246, 48, 47, 13));
        doubleSpinBox_65 = new QDoubleSpinBox(tab_9);
        doubleSpinBox_65->setObjectName(QStringLiteral("doubleSpinBox_65"));
        doubleSpinBox_65->setEnabled(false);
        doubleSpinBox_65->setGeometry(QRect(101, 124, 62, 22));
        doubleSpinBox_65->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_65->setMaximum(300);
        doubleSpinBox_66 = new QDoubleSpinBox(tab_9);
        doubleSpinBox_66->setObjectName(QStringLiteral("doubleSpinBox_66"));
        doubleSpinBox_66->setEnabled(false);
        doubleSpinBox_66->setGeometry(QRect(281, 44, 62, 22));
        doubleSpinBox_66->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_66->setMaximum(300);
        label_114 = new QLabel(tab_9);
        label_114->setObjectName(QStringLiteral("label_114"));
        label_114->setGeometry(QRect(51, 48, 47, 13));
        label_116 = new QLabel(tab_9);
        label_116->setObjectName(QStringLiteral("label_116"));
        label_116->setGeometry(QRect(245, 127, 47, 16));
        label_110 = new QLabel(tab_9);
        label_110->setObjectName(QStringLiteral("label_110"));
        label_110->setGeometry(QRect(51, 128, 47, 13));
        frame_20 = new QFrame(tab_9);
        frame_20->setObjectName(QStringLiteral("frame_20"));
        frame_20->setGeometry(QRect(210, 100, 161, 71));
        frame_20->setFrameShape(QFrame::StyledPanel);
        frame_20->setFrameShadow(QFrame::Raised);
        label_111 = new QLabel(frame_20);
        label_111->setObjectName(QStringLiteral("label_111"));
        label_111->setGeometry(QRect(50, 0, 101, 16));
        frame_21 = new QFrame(tab_9);
        frame_21->setObjectName(QStringLiteral("frame_21"));
        frame_21->setGeometry(QRect(30, 100, 161, 71));
        frame_21->setFrameShape(QFrame::StyledPanel);
        frame_21->setFrameShadow(QFrame::Raised);
        label_115 = new QLabel(frame_21);
        label_115->setObjectName(QStringLiteral("label_115"));
        label_115->setGeometry(QRect(30, 0, 101, 16));
        doubleSpinBox_64 = new QDoubleSpinBox(tab_9);
        doubleSpinBox_64->setObjectName(QStringLiteral("doubleSpinBox_64"));
        doubleSpinBox_64->setEnabled(false);
        doubleSpinBox_64->setGeometry(QRect(281, 124, 62, 22));
        doubleSpinBox_64->setProperty("showGroupSeparator", QVariant(false));
        doubleSpinBox_64->setMaximum(300);
        checkBox_11 = new QCheckBox(tab_9);
        checkBox_11->setObjectName(QStringLiteral("checkBox_11"));
        checkBox_11->setGeometry(QRect(30, 200, 121, 17));
        checkBox_11->setChecked(false);
        tabWidget->addTab(tab_9, QString());
        frame_21->raise();
        frame_18->raise();
        doubleSpinBox_67->raise();
        frame_19->raise();
        label_117->raise();
        doubleSpinBox_65->raise();
        doubleSpinBox_66->raise();
        label_114->raise();
        label_116->raise();
        label_110->raise();
        frame_20->raise();
        doubleSpinBox_64->raise();
        checkBox_11->raise();
        tab_10 = new QWidget();
        tab_10->setObjectName(QStringLiteral("tab_10"));
        checkBox_12 = new QCheckBox(tab_10);
        checkBox_12->setObjectName(QStringLiteral("checkBox_12"));
        checkBox_12->setGeometry(QRect(10, 200, 121, 17));
        checkBox_12->setChecked(false);
        tabWidget->addTab(tab_10, QString());
        pushButton = new QPushButton(NewEntForm);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(231, 297, 75, 23));
        pushButton_2 = new QPushButton(NewEntForm);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(321, 297, 75, 23));
        line_2 = new QFrame(NewEntForm);
        line_2->setObjectName(QStringLiteral("line_2"));
        line_2->setGeometry(QRect(11, 282, 631, 16));
        line_2->setFrameShape(QFrame::HLine);
        line_2->setFrameShadow(QFrame::Sunken);

        retranslateUi(NewEntForm);

        tabWidget->setCurrentIndex(6);
        comboBox->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(NewEntForm);
    } // setupUi

    void retranslateUi(QWidget *NewEntForm)
    {
        NewEntForm->setWindowTitle(QApplication::translate("NewEntForm", "Entity Data", nullptr));
        checkBox->setText(QApplication::translate("NewEntForm", "Include component", nullptr));
        doubleSpinBox_3->setSpecialValueText(QString());
        label->setText(QApplication::translate("NewEntForm", "X Position", nullptr));
        label_2->setText(QApplication::translate("NewEntForm", "Y Position", nullptr));
        doubleSpinBox_2->setSpecialValueText(QString());
        doubleSpinBox->setSpecialValueText(QString());
        label_3->setText(QApplication::translate("NewEntForm", "Z Position", nullptr));
        doubleSpinBox_8->setSpecialValueText(QString());
        label_8->setText(QApplication::translate("NewEntForm", "X Position", nullptr));
        label_9->setText(QApplication::translate("NewEntForm", "Y Position", nullptr));
        doubleSpinBox_9->setSpecialValueText(QString());
        doubleSpinBox_10->setSpecialValueText(QString());
        label_10->setText(QApplication::translate("NewEntForm", "Z Position", nullptr));
        doubleSpinBox_18->setSpecialValueText(QString());
        label_18->setText(QApplication::translate("NewEntForm", "X Position", nullptr));
        label_19->setText(QApplication::translate("NewEntForm", "Y Position", nullptr));
        doubleSpinBox_19->setSpecialValueText(QString());
        doubleSpinBox_20->setSpecialValueText(QString());
        label_20->setText(QApplication::translate("NewEntForm", "Z Position", nullptr));
        doubleSpinBox_21->setSpecialValueText(QString());
        label_21->setText(QApplication::translate("NewEntForm", "X Position", nullptr));
        label_22->setText(QApplication::translate("NewEntForm", "Y Position", nullptr));
        doubleSpinBox_22->setSpecialValueText(QString());
        doubleSpinBox_23->setSpecialValueText(QString());
        label_23->setText(QApplication::translate("NewEntForm", "Z Position", nullptr));
        radioButton->setText(QApplication::translate("NewEntForm", "Static Entity", nullptr));
        doubleSpinBox_4->setSpecialValueText(QString());
        label_4->setText(QApplication::translate("NewEntForm", "Rotation", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab), QApplication::translate("NewEntForm", "Position", nullptr));
        doubleSpinBox_24->setSpecialValueText(QString());
        label_24->setText(QApplication::translate("NewEntForm", "X Velocity", nullptr));
        label_25->setText(QApplication::translate("NewEntForm", "Y Velocity", nullptr));
        doubleSpinBox_25->setSpecialValueText(QString());
        doubleSpinBox_26->setSpecialValueText(QString());
        label_26->setText(QApplication::translate("NewEntForm", "Z Velocity", nullptr));
        doubleSpinBox_27->setSpecialValueText(QString());
        label_27->setText(QApplication::translate("NewEntForm", "X Bouyancy", nullptr));
        doubleSpinBox_28->setSpecialValueText(QString());
        doubleSpinBox_29->setSpecialValueText(QString());
        label_28->setText(QApplication::translate("NewEntForm", "Y Bouyancy", nullptr));
        label_29->setText(QApplication::translate("NewEntForm", "Z Bouyancy", nullptr));
        checkBox_3->setText(QApplication::translate("NewEntForm", "Include component", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_2), QApplication::translate("NewEntForm", "Velocity", nullptr));
        doubleSpinBox_30->setSpecialValueText(QString());
        label_30->setText(QApplication::translate("NewEntForm", "X Accel", nullptr));
        label_31->setText(QApplication::translate("NewEntForm", "Y Accel", nullptr));
        doubleSpinBox_31->setSpecialValueText(QString());
        doubleSpinBox_32->setSpecialValueText(QString());
        label_32->setText(QApplication::translate("NewEntForm", "Z Accel", nullptr));
        doubleSpinBox_33->setSpecialValueText(QString());
        label_33->setText(QApplication::translate("NewEntForm", "Mass", nullptr));
        checkBox_4->setText(QApplication::translate("NewEntForm", "Include component", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_3), QApplication::translate("NewEntForm", "Acceleration", nullptr));
        label_34->setText(QApplication::translate("NewEntForm", "Frames", nullptr));
        label_35->setText(QApplication::translate("NewEntForm", "Start ", nullptr));
        label_36->setText(QApplication::translate("NewEntForm", "Index", nullptr));
        comboBox->setItemText(0, QApplication::translate("NewEntForm", "Rotation", nullptr));
        comboBox->setItemText(1, QApplication::translate("NewEntForm", "Frame", nullptr));

        comboBox->setCurrentText(QApplication::translate("NewEntForm", "Rotation", nullptr));
        label_37->setText(QApplication::translate("NewEntForm", "Type", nullptr));
        checkBox_5->setText(QApplication::translate("NewEntForm", "Include component", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_4), QApplication::translate("NewEntForm", "Animation", nullptr));
        label_38->setText(QApplication::translate("NewEntForm", " MaxHealth", nullptr));
        label_39->setText(QApplication::translate("NewEntForm", "Lives", nullptr));
        checkBox_10->setText(QApplication::translate("NewEntForm", "Include component", nullptr));
        checkBox_6->setText(QApplication::translate("NewEntForm", "Include component", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_5), QApplication::translate("NewEntForm", "Health", nullptr));
        label_40->setText(QApplication::translate("NewEntForm", "Time On", nullptr));
        label_41->setText(QApplication::translate("NewEntForm", "Time Off", nullptr));
        radioButton_2->setText(QApplication::translate("NewEntForm", "Constant Loop", nullptr));
        checkBox_7->setText(QApplication::translate("NewEntForm", "Include component", nullptr));
        comboBox_2->setItemText(0, QApplication::translate("NewEntForm", "Disable Entity", nullptr));

        label_42->setText(QApplication::translate("NewEntForm", "Looped Off Logic", nullptr));
        comboBox_3->setItemText(0, QApplication::translate("NewEntForm", "Disbale Entity", nullptr));
        comboBox_3->setItemText(1, QApplication::translate("NewEntForm", "Destroy Entity", nullptr));
        comboBox_3->setItemText(2, QApplication::translate("NewEntForm", "Out of Time", nullptr));

        label_43->setText(QApplication::translate("NewEntForm", "Constant Off Logic", nullptr));
        comboBox_4->setItemText(0, QApplication::translate("NewEntForm", "None", nullptr));

        label_44->setText(QApplication::translate("NewEntForm", "On Logic", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_6), QApplication::translate("NewEntForm", "Timed", nullptr));
        label_45->setText(QApplication::translate("NewEntForm", "Elasticity", nullptr));
        doubleSpinBox_37->setSpecialValueText(QString());
        checkBox_8->setText(QApplication::translate("NewEntForm", "Include component", nullptr));
        checkBox_2->setText(QApplication::translate("NewEntForm", "Lethal", nullptr));
        checkBox_13->setText(QApplication::translate("NewEntForm", "Floor", nullptr));
        checkBox_14->setText(QApplication::translate("NewEntForm", "Impulse", nullptr));
        checkBox_15->setText(QApplication::translate("NewEntForm", "Breakable", nullptr));
        checkBox_16->setText(QApplication::translate("NewEntForm", "Hiding", nullptr));
        checkBox_17->setText(QApplication::translate("NewEntForm", "Moving", nullptr));
        groupBox->setTitle(QApplication::translate("NewEntForm", "Collision Type", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_7), QApplication::translate("NewEntForm", "Collision", nullptr));
        doubleSpinBox_40->setSpecialValueText(QString());
        doubleSpinBox_41->setSpecialValueText(QString());
        label_47->setText(QApplication::translate("NewEntForm", "Height", nullptr));
        label_48->setText(QApplication::translate("NewEntForm", "Width", nullptr));
        label_49->setText(QApplication::translate("NewEntForm", "Image Index", nullptr));
        label_50->setText(QApplication::translate("NewEntForm", "Repeat", nullptr));
        comboBox_6->setItemText(0, QApplication::translate("NewEntForm", "Background", nullptr));
        comboBox_6->setItemText(1, QApplication::translate("NewEntForm", "Main", nullptr));

        label_51->setText(QApplication::translate("NewEntForm", "Sprite Type", nullptr));
        checkBox_9->setText(QApplication::translate("NewEntForm", "Include component", nullptr));
        pushButton_4->setText(QApplication::translate("NewEntForm", "Select Sprite", nullptr));
        radioButton_3->setText(QApplication::translate("NewEntForm", "Activated from start", nullptr));
        label_52->setText(QApplication::translate("NewEntForm", "Texture x", nullptr));
        doubleSpinBox_42->setSpecialValueText(QString());
        doubleSpinBox_43->setSpecialValueText(QString());
        label_53->setText(QApplication::translate("NewEntForm", "Texture y", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_8), QApplication::translate("NewEntForm", "Sprite", nullptr));
        label_119->setText(QApplication::translate("NewEntForm", "Move Acceleration", nullptr));
        doubleSpinBox_67->setSpecialValueText(QString());
        label_118->setText(QApplication::translate("NewEntForm", "Move Velocity", nullptr));
        label_117->setText(QApplication::translate("NewEntForm", "X Vel", nullptr));
        doubleSpinBox_65->setSpecialValueText(QString());
        doubleSpinBox_66->setSpecialValueText(QString());
        label_114->setText(QApplication::translate("NewEntForm", "X Accel", nullptr));
        label_116->setText(QApplication::translate("NewEntForm", "X Vel", nullptr));
        label_110->setText(QApplication::translate("NewEntForm", "X Accel", nullptr));
        label_111->setText(QApplication::translate("NewEntForm", "Jump Velocity", nullptr));
        label_115->setText(QApplication::translate("NewEntForm", "Jump Acceleration", nullptr));
        doubleSpinBox_64->setSpecialValueText(QString());
        checkBox_11->setText(QApplication::translate("NewEntForm", "Include component", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_9), QApplication::translate("NewEntForm", "Player", nullptr));
        checkBox_12->setText(QApplication::translate("NewEntForm", "Include component", nullptr));
        tabWidget->setTabText(tabWidget->indexOf(tab_10), QApplication::translate("NewEntForm", "Input", nullptr));
        pushButton->setText(QApplication::translate("NewEntForm", "Cancel", nullptr));
        pushButton_2->setText(QApplication::translate("NewEntForm", "Ok", nullptr));
    } // retranslateUi

};

namespace Ui {
    class NewEntForm: public Ui_NewEntForm {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_NEWENTITY_H
